// Module included in the following assemblies:
//
// * virt/node_network/virt-configuring-node-network-policy

[id="virt-confirming-policy-updates-on-nodes_{context}"]
= Confirming policy updates on nodes

A `NodeNetworkConfigurationPolicy` manifest describes your requested network configuration for nodes in the cluster.
The policy object includes your requestd network configuration and the status of execution of the Policy on the cluster as a whole.


When you apply a policy, a `NodeNetworkConfigurationEnactment` is created for every node in the cluster. The Enactment is a read-only object that represents the status of execution of the Policy on that node.
If the policy fails to be applied on the node, the enactment for that node includes a traceback for troubleshooting.

.Procedure

. To confirm that a policy has been applied to the cluster, list the Policies and their status:
+
[source,terminal]
----
$ oc get nncp
----

. (Optional) If a policy is taking longer than expected to successfully configure, you can inspect the requested state and status conditions of a particular Policy:
+
[source,terminal]
----
$ oc get nncp <policy> -o yaml
----

. (Optional) If a policy is taking longer than expected to successfully configure on all nodes, you can list the status of the enactments on the cluster:
+
[source,terminal]
----
$ oc get nnce
----

. (Optional) To view the configuration of a particular enactment, including any error reporting for a failed configuration:
+
[source,terminal]
----
$ oc get nnce <node>.<policy> -o yaml
----
